# Generated by Django 6.1 on 2026-08-31 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standard_break_minutes', models.PositiveIntegerField(default=60)),
                ('shift_start_time', models.TimeField(default='09:00:00')),
                ('standard_shift_minutes', models.PositiveIntegerField(default=480)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_percent', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company')),
                ('hod', models.OneToOneField(blank=True, limit_choices_to={'role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_headed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('LEAVE', 'Leave Policy'), ('ATTENDANCE', 'Attendance Policy'), ('OVERTIME', 'Overtime Policy'), ('PAYROLL', 'Payroll Rules'), ('GENERAL', 'Company Guidelines')], default='GENERAL', max_length=20)),
                ('file', models.FileField(upload_to='policy_documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_policies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
