from django.db import models


class AIConversation(models.Model):
    employee = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="ai_conversations"
    )
    started_at = models.DateTimeField(auto_now_add=True)
    # Free-form scratchpad for in-progress multi-turn workflows (e.g. leave
    # request fields collected so far). Small, ephemeral, not a long-term
    # memory system - cleared once the workflow completes.
    pending_workflow = models.JSONField(null=True, blank=True)
    # Legacy provider state retained for database compatibility. The current
    # AI provider is Groq; this field is no longer used by the runtime.
    gemini_interaction_id = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"AIConversation({self.employee}, #{self.pk})"


class AIMessage(models.Model):
    class Role(models.TextChoices):
        USER = "USER", "User"
        ASSISTANT = "ASSISTANT", "Assistant"
        TOOL = "TOOL", "Tool"

    conversation = models.ForeignKey(AIConversation, on_delete=models.CASCADE, related_name="messages")
    role = models.CharField(max_length=20, choices=Role.choices)
    content = models.TextField()
    tool_name = models.CharField(max_length=100, blank=True)
    tool_result = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.role}: {self.content[:50]}"


class KnowledgeChunk(models.Model):
    """
    Searchable chunks of a company PolicyDocument's extracted text.
    Search backend is abstracted (see ai/knowledge.py) so SQLite (icontains,
    current dev DB) and Postgres (full-text search, later migration) both
    work without changing calling code.
    """

    policy_document = models.ForeignKey(
        "company.PolicyDocument", on_delete=models.CASCADE, related_name="knowledge_chunks"
    )
    chunk_index = models.PositiveIntegerField()
    chunk_text = models.TextField()
    # Optional normalized sentence embedding serialized as JSON. Kept empty when
    # the semantic retrieval dependency/model is unavailable; lexical retrieval
    # remains the safe fallback.
    semantic_embedding = models.TextField(blank=True, default="")

    class Meta:
        ordering = ["policy_document", "chunk_index"]

    def __str__(self):
        return f"{self.policy_document.title} #{self.chunk_index}"


class AIActionExecution(models.Model):
    """Durable idempotency record for side-effecting AI tool calls.

    The key is generated by the server from the authenticated user, action
    identity and stable turn/call identifiers; model-supplied user ids are
    never part of the authority boundary.
    """
    class Status(models.TextChoices):
        PROCESSING = "PROCESSING", "Processing"
        SUCCEEDED = "SUCCEEDED", "Succeeded"
        FAILED = "FAILED", "Failed"

    key = models.CharField(max_length=128, unique=True)
    conversation = models.ForeignKey(AIConversation, on_delete=models.CASCADE, null=True, blank=True, related_name="action_executions")
    tool_name = models.CharField(max_length=100)
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PROCESSING)
    result = models.JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [models.Index(fields=["conversation", "tool_name", "created_at"])]
